config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'posts/:id', to: 'posts#show', as: 'post'
  get 'tags/:tag', to: 'welcome#index', as: :tag

  root 'welcome#index'

  get '*path' => redirect('/')
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_taggable

  validates :title, presence: true
  validates :content, presence: true

  scope :desc, lambda {
    order('posts.created_at DESC')
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :find_post, only: [:show]

  def show; end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    posts = welcome_params ? Post.tagged_with(welcome_params) : Post.all
    @posts = posts.desc.paginate(page: params[:page], per_page: 5).decorate

    @tags = ActsAsTaggableOn::Tag.all
  end

  private

  def welcome_params
    params[:tag]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include ActsAsTaggableOn::TagsHelper

  def body_class
    controller.controller_name.to_s
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    # :reek:UtilityFunction
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

  def options
    {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
  end
end

app/views/layouts/_error_messages.html.haml
.notice-alert-messages
  - if notice
    %p#notice= notice
  - elsif alert
    %p#alert= alert

app/views/layouts/_ga.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60775504-1');

app/views/layouts/_nav.html.haml
%header.main-navigation.clearfix
  = link_to 'Jared Gray', root_path, class: 'name'

  .social-links
    %a{ href: 'http://github.com/jd-gray', target: '_blank' }
      %i.fa.fa-github
    %a{ href: 'http://stackoverflow.com/users/4735914/jdgray?tab=profile', target: '_blank' }
      %i.fa.fa-stack-overflow
    %a{ href: 'https://www.linkedin.com/in/jareddgray', target: '_blank' }
      %i.fa.fa-linkedin

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Jared Gray

    %link{ href: 'https://fonts.googleapis.com/css?family=Open+Sans:400,700', rel: 'stylesheet' }

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %meta{ name: 'description', content: 'Ruby on Rails developer based in Phoenix, AZ' }

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

    = render 'layouts/ga'

    = csrf_meta_tags

    = favicon_link_tag 'favicon.ico'

  %body{ class: body_class }
    = render 'layouts/nav'

    = yield

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'jaredgrayblog';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/show.html.haml
.skinny-wrapper.content
  %header
    %p.date= @post.created_at.strftime('%A, %B %d')
    = @post.title
    %hr

  #content
    = markdown @post.content

app/views/welcome/index.html.haml
.row
  .posts.text-center.col-md-8
    - @posts.each do |post|
      %h3= link_to post.title, post
      %p.date= post.created_at
      %p= post.content
      %br
      - post.tags.each do |tag|
        %span.badge= link_to tag.name, tag_path(tag: tag.name)
      %hr

  .jumbotron.col-md-3
    - @tags.each do |tag|
      %span.badge= link_to tag.name, tag_path(tag: tag.name)

  = will_paginate @posts